swipe:
  3: 
    left: 
      command: 'xdotool key Super+shift+Tab'
    right: 
      command: 'xdotool key XF86AudioPlay'
    up: 
      command: 'xdotool key super'
    down: 
      command: 'xdotool key super+d'
  4:
    left: 
      command: 'xdotool key XF86AudioNext'
    right: 
      command: 'xdotool key XF86AudioPrev'
    up: 
      command: 'xdotool key XF86AudioRaiseVolume'
    down: 
      command: 'xdotool key XF86AudioLowerVolume'

pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
     command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
